Validate translations
dodona-edu/papyros pull request #54
Opened 2021-12-01 21:01 UTC by winniederidder

This PR adds a JS script called ValidateTranslations that checks whether the provided translations are valid (not missing or unused). A GitHub action is also defined to call this script on pushes to any branch.

The script is written in JavaScript as running it as a stand-alone TS file never fully worked. On the one hand, i18n-extract does not provide proper typing, requiring some hacks to get it into TypeScript (e.g. including the source code directly as it required some manual editing to even run). On the other hand, importing other modules did not work out of the box.
The JavaScript file can easily be run through Node, but the Translations.ts file had to be converted to JS for it to be imported. This isn't an impactful change, as they are simple objects where typing is quite irrelevant.

The biggest issue with this approach is the presence of dynamic keys (e.g. used in displaying the Papyros state or the programming languages) so the static analysis approach cannot really work with this and thus concludes everything is used. @bmesuere Thoughts on this? These could be made explicit (at the loss of some code compactness)

Would close #53

2021-12-03 16:21 UTC, bmesuere reviewed
👍 Looks good. Do we also want to check for unused translations? Maybe in that case, we shouldn't error, but we can add them as annotations to the code, e.g. using https://github.com/pytorch/add-annotations-github-action

2021-12-03 18:45 UTC, winniederidder commented
> 👍 Looks good. Do we also want to check for unused translations? Maybe in that case, we shouldn't error, but we can add them as annotations to the code, e.g. using https://github.com/pytorch/add-annotations-github-action

Not entirely sure how these annotations would work. Unused translations would only be present in the Translations.js file. How would these be added?

Regarding my question to the issue with dynamic translation keys (with interpolated strings causing the static analysis to deem everything used), how do you think we best tackle that? I think it would be possible to make these explicit, which would make the analysis more useful.

2021-12-04 13:44 UTC, bmesuere commented
Regarding annotations: the action I linked lets you add github annotations (by writing filename, line number and message to a file). They then show up in the github UI. In this case, I would add such annotation to the lines containing unused translations.

Regarding dynamic translation keys: what is your question exactly? I probably missed it somewhere.

2021-12-04 14:23 UTC, winniederidder commented
> Regarding annotations: the action I linked lets you add github annotations (by writing filename, line number and message to a file). They then show up in the github UI. In this case, I would add such annotation to the lines containing unused translations.

I will take a look then, thanks!

> Regarding dynamic translation keys: what is your question exactly? I probably missed it somewhere.

I edited the original post so the question wasn't there anymore. In essence, if dynamic translation keys are used (i.e string interpolation in the translation key like `Papyros.${programmingLanguage}`) then this script becomes quite useless. It employs static analysis and cannot determine which values could be passed here, so it deems every key used. My question was thus whether we want to forbid dynamic keys. This might be a bit of a hassle for the programmer, but it does allow static analysis to be useful. I opted to indeed let go of dynamic keys and added the forbidDynamic check to the script to make this clear.

2021-12-05 10:43 UTC, bmesuere commented
Ok now I see. I think this is why they often have nested keys, e.g. papyros.programming_language.${language}, then only do interpolation in such subkeys.

2021-12-05 11:41 UTC, winniederidder commented
> Ok now I see. I think this is why they often have nested keys, e.g. papyros.programming_language.${language}, then only do interpolation in such subkeys.

That indeed sounds like it could work. Do you want me to integrate that, or keep this as this is and merge it?

2021-12-05 11:45 UTC, bmesuere commented
It seems cleaner to have nested translations to be able to group things, no?

2021-12-06 12:07 UTC, winniederidder commented
@bmesuere This branch should now also add annotations to files where a certain kind of translation issue was detected. It is thus ready for review and hopefully merging.

2021-12-06 14:40 UTC, bmesuere requested changes
I wanted to test this (by adding a manual trigger to the GH Action), but it seems there is a syntax error in the workflow file. In addition, the name of the action looks funny in the GH Actions menu, so double check.

I would also temporarily add an extra translation key to check if the annotation shows up in the GitHub UI.

2021-12-06 15:49 UTC, winniederidder commented
@bmesuere Annotations from testing are available on https://github.com/dodona-edu/papyros/actions/runs/1545351976, but I am not exactly sure how to use them properly. Is this our expected output, or am I misinterpreting something?

2021-12-06 16:22 UTC, winniederidder commented
@bmesuere Annotations are now present in the "files changed" tab. Once you agree with the formatting, I can remove the testing keys and then this can be merged?

2021-12-06 16:26 UTC, bmesuere approved these changes
nice, looks good!

2021-12-06 16:30 UTC, merged